version: '3.9'
services:
  bot:
    build: .
    container_name: arbitrage-bot
    env_file:
      - .env
    volumes:
      - .:/app
    command: python -u -m src
    environment:
      - PYTHONPATH=/app/src